services:
  - type: web
    name: klarifikasi-backend
    runtime: php
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: GOOGLE_CSE_KEY
        value: AIzaSyAFOdoaMwgurnjfnhGKn5GFy6_m2HKiGtA
      - key: GOOGLE_CSE_CX
        value: 6242f5825dedb4b59
      - key: GOOGLE_CSE_VERIFY_SSL
        value: false
